#!/usr/bin/env bash
# Syncs live/team-<name>/ folders with teams.yaml.
#   sync  (default): create missing folders, (re)write the generated terragrunt.hcl,
#                    create a starter team.yaml only if none exists.
#   check          : change nothing; exit 1 if anything is out of sync or a team.yaml
#                    is missing required fields (for CI).
# Never deletes folders: a folder whose name was removed from teams.yaml is
# "pending offboarding" until CI has destroyed the team (see scripts/offboard-team.sh).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REGISTRY="$ROOT/teams.yaml"
LIVE="$ROOT/live"
MODE="${1:-sync}"
NAME_RE='^[a-z0-9]([a-z0-9-]{0,13}[a-z0-9])?$'
RESERVED=" tfstate github ci admin platform root "

case "$MODE" in sync | check) ;; *) echo "usage: $0 [sync|check]" >&2; exit 2 ;; esac
command -v yq >/dev/null || { echo "yq (mikefarah/yq v4) is required" >&2; exit 2; }

TERRAGRUNT_HCL='# Generated by `make teams` from teams.yaml. Do not edit: team settings live in team.yaml.
include "root" {
  path = find_in_parent_folders("root.hcl")
}
'

starter_team_yaml() {
  cat <<EOF
# Settings for team "$1", read by live/root.hcl. Owned by the team.
# owner, cost_center and buckets are empty on purpose: checks fail until they are filled in.
owner: ""       # contact e-mail or handle
cost_center: "" # cost allocation
buckets: []     # e.g. - { suffix: data, visibility: private }   visibility: public | private
# Who may assume the team role. "{account_id}" is resolved by live/root.hcl.
# Default = this account, access delegated to IAM policies; narrow to Terraform-managed role ARNs if needed.
trusted_principal_arns:
  - "arn:aws:iam::{account_id}:root"
tags:
  ManagedBy: terraform
EOF
}

# Offline content checks; the module re-validates everything at plan time.
check_team_yaml() {
  local f="$1" label="$2"
  yq -e '.' "$f" >/dev/null 2>&1 || { fail "$label: team.yaml is not valid YAML"; return; }
  [ -n "$(yq -r '.owner // ""' "$f")" ] || fail "$label: owner is required"
  [ -n "$(yq -r '.cost_center // ""' "$f")" ] || fail "$label: cost_center is required"
  [ "$(yq -r '.buckets // [] | length' "$f")" -gt 0 ] || fail "$label: at least one bucket is required"
  [ "$(yq -r '.buckets // [] | map(select(.visibility != "public" and .visibility != "private")) | length' "$f")" -eq 0 ] ||
    fail "$label: every bucket needs visibility: public or private"
  [ "$(yq -r '.trusted_principal_arns // [] | length' "$f")" -gt 0 ] || fail "$label: trusted_principal_arns is required"
  [ "$(yq -r '.tags.ManagedBy // ""' "$f")" = terraform ] || fail "$label: tags.ManagedBy must be terraform"
}

yq -e '.teams | tag == "!!seq"' "$REGISTRY" >/dev/null 2>&1 || {
  echo "error: $REGISTRY must contain a 'teams:' list" >&2
  exit 1
}
names="$(yq -r '.teams[]' "$REGISTRY")"

errors=0
fail() { echo "error: $*" >&2; errors=$((errors + 1)); }

dupes="$(printf '%s\n' "$names" | sort | uniq -d)"
[ -z "$dupes" ] || fail "duplicate team names in teams.yaml: $(echo $dupes)"

for name in $names; do
  if [[ ! "$name" =~ $NAME_RE ]]; then fail "invalid team name '$name'"; continue; fi
  if [[ "$RESERVED" == *" $name "* ]]; then fail "team name '$name' is reserved"; continue; fi

  dir="$LIVE/team-$name"
  if [ "$MODE" = check ]; then
    [ -d "$dir" ] || { fail "team-$name: folder missing (run: make teams)"; continue; }
    printf '%s' "$TERRAGRUNT_HCL" | cmp -s - "$dir/terragrunt.hcl" ||
      fail "team-$name: terragrunt.hcl missing or modified (run: make teams)"
    if [ -f "$dir/team.yaml" ]; then
      check_team_yaml "$dir/team.yaml" "team-$name"
    else
      fail "team-$name: team.yaml missing (run: make teams)"
    fi
  else
    mkdir -p "$dir"
    if ! printf '%s' "$TERRAGRUNT_HCL" | cmp -s - "$dir/terragrunt.hcl" 2>/dev/null; then
      printf '%s' "$TERRAGRUNT_HCL" >"$dir/terragrunt.hcl"
      echo "wrote   live/team-$name/terragrunt.hcl"
    fi
    if [ ! -f "$dir/team.yaml" ]; then
      starter_team_yaml "$name" >"$dir/team.yaml"
      echo "created live/team-$name/team.yaml (fill in owner, cost_center, buckets; then run make check-teams)"
    fi
  fi
done

for dir in "$LIVE"/team-*/; do
  [ -d "$dir" ] || continue
  name="$(basename "$dir")"
  name="${name#team-}"
  # A folder without a registry entry is the offboarding queue: CI destroys the team,
  # then opens a PR deleting the folder.
  if ! printf '%s\n' "$names" | grep -qx -- "$name"; then
    echo "notice: team-$name is not in teams.yaml: pending offboarding (CI destroys it, then opens a PR removing the folder)" >&2
  fi
done

[ "$errors" -eq 0 ] || { echo "$errors problem(s) found" >&2; exit 1; }
[ "$MODE" = check ] && echo "live/ is in sync with teams.yaml" || true
